INSERT INTO Questions (quiz_id, subject, question_text, image_url, audio_url )
VALUES (1, 'Mathematics', '2+2 = ?', '', ''),
       (1, 'Mathematics', '1+2 = ?', '', ''),
       (1, 'Mathematics', 'How do you write two in numeral form?', '', ''),
       (1, 'Mathematics','What is a number in the tens place?', '', ''),
       (1, 'Mathematics', 'What does cm stands for in measurements?', '',''),
       (1, 'Mathematics', 'What does mm stands for in measurements?', '',''),
       (1, 'Mathematics', 'There are 4 red balls and 2 blue balls. How many balls are there in total?', '', ''),
       (1, 'Mathematics', 'You have 2 pencils and your friend gives you 4 more pencils. How many pencils do you have now?', '', ''),
       (1, 'Mathematics', 'There are 6 children in a class. If 2 more children join the class, how many children are in the class now?', '', ''),
       (1, 'Mathematics', 'Which is bigger 1 cm or 1 inch?', '', ''),
       (1, 'Mathematics', 'How much is a Penny worth in cents?', '', ''),
       (1, 'Mathematics', 'How many minutes is a quarter of an hour?', '', ''),
       (1, 'Mathematics', 'How much is a Quarter worth in cents?', '', ''),
       (1, 'Mathematics', 'Where are decimals located in a number?', '', ''),
       (1, 'Mathematics', 'What is 50% of 10?', '', ''),
       (1, 'Mathematics', 'Which coin does the image show?', 'https://upload.wikimedia.org/wikipedia/en/0/0f/2022_Washington_quarter_obverse.jpeg', ''),
       (1, 'Mathematics', 'How many sides does a pentagon have?', '', '')
       (1, 'Mathematics', 'How many sides does a square have?', '', '')
       (1, 'Mathematics', 'What shape is a stop sign?', '', '')
       (2, 'Science', 'What is another name for fall?', '', ''),
       (2, 'Science', 'Which organ covers the entire body and protects it?', '', ''),
       (2, 'Science,' 'What is a baby cow called?', '',''),
       (2, 'Science,' 'What is the boiling point of water in Celcius?', '',''),
       (2, 'Science,' 'What group of animals have scales?', '',''),
       (2, 'Science,' 'What is the boiling point of water in Fahrenheit?', '',''),
       (2, 'Science,' 'A male cow is called what?', '',''),
       (2, 'Science,' 'Which bird lays the biggest eggs?', '',''),
       (2, 'Science','What type of bird eats animals that are already dead?', '',''),
       (3, 'History', 'How many states are there in the U.S.?', '', ''),
       (3, 'History', 'Which U.S. city is known as “the windy city”?', '', ''),
       (3, 'History', 'Which is the smallest U.S. state?'),
       (3, 'History', 'Which U.S. state is known as the sunflower state?', '', ''),
       (3, 'History', 'What is Las Vegas famous for?', '', ''),
       (3, 'History', 'In which state would you find the Grand Canyon?', '', ''),
       (3, 'History', 'Who was the first president of the United State?', '', ''),
       (3, 'History', 'What year was the Declaration Of Independence signed?', '', ''),
       (3, 'History', 'What is the name of the U.S national anthem?', '', ''),
       (3, 'History', 'How old do you have to be to vote?', '', '')
       ;
